#!/usr/bin/env bash

export CONTECO_LABEL="package.kafka_connect_sasl - ModEco"
export CONTECO_DESCRIPTION="Modeco Confluent Kafka Connect package, with SASL authentication."

export CONTECO_TYPE="package"
export CONTECO_NAME="kafka_connect_sasl"
export CONTECO_TAG="5.4.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
