#!/usr/bin/env bash

export CONTECO_LABEL="package.kafka_connect_tocloud - ModEco"
export CONTECO_DESCRIPTION="Modeco Confluent Kafka Connect to cloud module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="kafka_connect_tocloud"
export CONTECO_TAG="5.4.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
