#!/usr/bin/env bash


prefix="package_kafka_connect_sasl_$2"

if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_secrets_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_connect_secrets_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_data_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_jars_volume
	fi
	
