#!/usr/bin/env bash


prefix="package_kafka_connect_sasl_$2"

if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_secrets_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_connect_secrets_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_data_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_jars_volume
	fi
	
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_connect_secrets_volume:/etc/kafka-connect/secrets ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/kafka_connect_sasl_kafka_connect_connect_secrets_volume.tar
		fi
		
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_secrets_volume:/etc/kafka/secrets ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/kafka_connect_sasl_kafka_connect_secrets_volume.tar
		fi
		
if [[ "package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_jars_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v package_kafka_connect_sasl_kafka_connect_sasl_kafka_connect_jars_volume:/etc/kafka-connect/jars ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/kafka_connect_sasl_kafka_connect_jars_volume.tar
		fi
		
