#!/usr/bin/env bash


prefix="package_$2"

if [[ "_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_connect_secrets_volume
	fi
	
if [[ "_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_connect_connect_secrets_volume
	fi
	
if [[ "_kafka_connect_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_connect_data_volume
	fi
	
if [[ "_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_connect_jars_volume
	fi
	
